In [1]:
import pandas as pd

In [13]:
popu = pd.read_csv("./data/Population-Smokers.csv")
big_year = popu[popu["Year"] == 2010]
big_year.to_csv("./data/Population-Smokers-2010.csv", index=False)

In [17]:
big_year.sort_values(by="Population")

,Entity,Code,Year,Prevalence of current tobacco use (% of adults),Population
758,Nauru,NRU,2010,55.500000,10067
1080,Tuvalu,TUV,2010,41.800000,10635
828,Palau,PLW,2010,21.400000,18418
681,Marshall Islands,MHL,2010,28.400000,52065
23,Andorra,AND,2010,34.000000,80726
...,...,...,...,...,...
450,High-income countries,NaN,2010,27.464682,1176862152
471,India,IND,2010,38.100000,1243481564
219,China,CHN,2010,26.200000,1351561511
1115,Upper-middle-income countries,NaN,2010,25.931273,2587239946
625,Lower-middle-income countries,NaN,2010,31.551897,2707862957

In [20]:
smokers = pd.read_csv("./data/Daily-Smokers.csv")
verybig = smokers[smokers['Year'] == 1997]
verybig.to_csv("./data/Population-Smokers-1997.csv", index=False)